#!/bin/bash

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "/usr/share/icons/Adwaita/16x16/devices/audio-speakers-symbolic.symbolic.png" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5 
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5 
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
		dunstify -i "/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png" -a "changevolume" -t 2000 -r 9993 -u low "Muted"
"/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png"
	else
		send_notification up
	fi
	;;
esac
